config/routes.rb
class Subdomain
  def self.matches?(request)
    request.subdomain.present? && request.subdomain != 'www'
  end
end

Bookthatapp::Application.routes.draw do
  root :to => 'home#index'

  mount StripeEvent::Engine => '/stripe' # gem 'stripe-event'

  devise_for :users, controllers: {
        sessions: 'users/sessions', registrations: "users/registrations"
      }
  resources :users

  get "locations/index"

  get 'status' => "home#status"
  get 'change_ui' => 'home#change_ui'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  scope '/hooks' do
    post 'shop/update'         => 'hooks#shop_update'
    post 'app/uninstalled'     => 'hooks#uninstall'
    post 'orders/create'       => 'hooks#order'
    post 'orders/paid'         => 'hooks#paid'
    post 'orders/cancelled'    => 'hooks#cancelled'
    post 'orders/update'       => 'hooks#orders_update'
    post 'products/update'     => 'hooks#update'
    post 'products/delete'     => 'hooks#delete'
    post 'mail'                => 'hooks#mail'
  end

  scope '/apps' do
    get 'bookthatapp(/:action(/:id))', :controller => 'proxy'
  end

  resources :calendar, only: [:index]
  get '/navigate(/:action(/:id))', :controller => 'navigate'

  constraints(Subdomain) do
    resources :events, only: [:index]

    resources :bookings do
      member do
        put 'reminder'
        put 'sms'
      end
      collection do
        post 'send_reminders', as: :send_reminders
      end
    end

    resources :resource_groups, :users, :product_imports, :blackouts, :locations, :accounts

    resources :shops do
      member do
        get 'locations'
      end
    end

    resources :resources do
      resources :schedules
    end


    resources :bookings do
      member do
        get 'ticket'
        get 'email_activity'
        post 'attendance', :constraints => {:format => /(json)/}
      end
    end

    resources :products do
      resources :reservations
      resources :waitlists
      resources :variants do
        post 'reset', :on => :collection
      end

      collection do
        get 'autocomplete'
      end
      resources :terms, except: [:index]
    end

    resource :availabilities, only: [:index], defaults: { format: 'json' } do
      collection do
        get 'capacity'
        get 'preview'
        get 'schedule'
      end
    end

    resources :templates do
      collection do
        get 'new_reminder'
      end
      member do
        get 'site'
        get 'email'
      end
    end

    resource :feedback, only: [:new, :create]
    resource :embed, only: [:new, :create]

    resources :charges do
      collection do
        patch 'approve_install'
        get 'confirm'
        get 'install'
        patch 'subscribe'
        patch 'cancel'
        get 'installation'
      end
    end

    post 'charges/cancelled(/:id)' => 'charges#cancelled', :as => :cancel_installation
    post 'charges/cancel_pending(/:id)' => 'charges#cancel_pending', :as => :cancel_pending_charge

    get '/shop/install' => 'shops#install'

    scope :reports do
      get 'runsheet' => 'reports#runsheet', :as => :runsheet
      get 'enrollments' => 'reports#enrollments', :as => :enrollments
      get 'gantt' => 'reports#gantt'
    end


    resource :javascripts, only: [:index] do
      member do
        get 'bta'
        get 'wizard'
      end
    end

    get 'settings' => 'settings#index'
    resource :settings, only: [:index] do
      member do
        get 'hours'
        post 'update'
        post 'update_hours'
      end
      # resource :hours
    end

    scope :doco do
      get 'install' => 'doco#install'
      get 'product' => 'doco#product'
      get 'cart' => 'doco#cart'
      get 'email' => 'doco#email'
      get 'compatibility' => 'doco#compatibility'
      get 'css' => 'doco#css'
      get 'themes' => 'doco#themes'
    end

    get '/tests/:action', :controller => 'tests'
    resources :reports

    scope '/admin', :as => :admin do
      get 'dashboard', to: 'events#index'
      get 'charges'              => 'charges#index'
      get 'charges/confirm'      => 'charges#confirm'
      get 'charges/install'      => 'charges#install'
      get 'charges/installation' => 'charges#installation'
      post 'charges/cancelled(/:id)'      => 'charges#cancelled', :as => :cancel_installation
      post 'charges/cancel_pending(/:id)' => 'charges#cancel_pending', :as => :cancel_pending_charge

      get 'events/resources' => 'events#resources'

      resources 'events', 'blackouts', 'locations'
      get 'reports/runsheet'      => 'reports#runsheet', :as => :runsheet
      get 'reports/enrollments'   => 'reports#enrollments', :as => :enrollments

      resources :reports

      resources :products do
        resources :reservations
        resources :waitlists
        resources :variants do
          post 'reset', :on => :collection
        end

        collection do
          get 'autocomplete'
        end
        resources :terms, except: [:index]
      end


      resources :product_imports
      resources :resources do
        resources :schedules
      end

      resources :templates do
        get 'new_reminder', :on => :collection
      end

      resources 'doco', only: [:index] do
        collection do
          get 'install'
          get 'cart'
          get 'picker'
          get 'product'
          get 'availability'
          get 'css'
          get 'widgets'
          get 'themes'
          post 'snippet'
          get 'email'
          get 'compatibility'
        end
      end

      resources :settings, only: [:index, :update] do
        post 'update_settings'
        collection do
          post 'update_hours'
          get 'hooks'
          get 'scripts'
          get 'hours'
        end
      end

      resources :bookings do
        member do
          put 'reminder'
          put 'sms'
        end
        collection do
          post 'send_reminders', as: :admin_send_reminders
        end
      end

    end


    match '/:controller(/:action(/:id))', via: [:get, :post, :patch]
  end

  namespace :api do
    namespace :v1 do
      get 'availability' => 'availability#index'
      resources :bookings, only: [:index, :show]
    end
  end

  get 'status' => 'home#status'
  get '/404' => 'errors#error_404'
  get '/422' => 'errors#error_422'
  get '/429' => 'errors#error_429'
  get '/500' => 'errors#error_500'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  get '/:controller(/:action(/:id))'

  # otherwise show not found
  get ':url' => 'application#not_found', :constraints => { :url => /.*/ }
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :shop
  serialize :fields, Array

  EVENT_ORDER_ID = 'order_id'
  BOOKING_ID = 'id'
  CUSTOMER_NAME = 'name'
  CUSTOMER_EMAIL = 'email'
  CUSTOMER_PHONE = 'phone'
  NOTES = 'notes'
  PRODUCT_TITLE = 'product_title'
  VARIANT_TITLE = 'title'
  QUANTITY = 'quantity'
  START = 'start'
  FINISH = 'finish'
  START_FINISH = 'start_finish'
  PRODUCT_WITH_VARIANT = 'product_variant'
  CUSTOMER_CONTACTS = 'customer_contact'

  FIELDS = {
      EVENT_ORDER_ID => { text: 'Order Number'},
      BOOKING_ID => { text: 'Booking ID'},
      CUSTOMER_NAME => { text: 'Customer Name'},
      CUSTOMER_EMAIL => { text: 'Customer Email'},
      CUSTOMER_PHONE => { text: 'Customer Phone'},
      NOTES => { text: 'Note'},
      PRODUCT_TITLE => { text: 'Product'},
      VARIANT_TITLE => { text: 'Variant'},
      QUANTITY => { text: 'Quantity'},
      START => { text: 'Start date'},
      FINISH => { text: 'Finish date'},
      START_FINISH => { text: 'Start/Finish dates'},
      PRODUCT_WITH_VARIANT => { text: 'Product with Variant'},
      CUSTOMER_CONTACTS => { text: 'Customer contacts'},
  }

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include BookThatAppUtils

  validates_presence_of :site, :subdomain

  # The reason that we use the subdomain as the unique identifier for a Shop, instead of
  # using the ActiveResource site value, is that the site value could change. If a shop were
  # to revoke access to your application and re-install it at a later date, it would get
  # a new password for your app and its site would change. It's subdomain however is
  # immutable and makes a better key for Shops.
  validates_uniqueness_of :subdomain
  validates_exclusion_of :subdomain, :in => %w(admin, www, shopify, conciergify, support, info, help, api, status)

  has_many :events
  has_many :event_dates, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :booking_items # booking destroys these
  has_many :incomplete_bookings, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :variants, through: :products
  has_many :product_imports, dependent: :destroy
  has_many :locations, dependent: :destroy
  accepts_nested_attributes_for :locations, :reject_if => lambda {|n| n[:name].blank? }, :allow_destroy => true
  has_many :templates, dependent: :destroy, :class_name => "LiquidTemplate"
  has_many :shop_notes, dependent: :destroy
  has_many :blackouts, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :resources, dependent: :destroy
  has_many :resource_groups, dependent: :destroy
  has_many :seasons, as: :hourable, dependent: :destroy
  has_many :email_events, inverse_of: :shop, dependent: :destroy
  has_many :reminder_configs, inverse_of: :shop, dependent: :destroy
  accepts_nested_attributes_for :reminder_configs, reject_if: :all_blank, :allow_destroy => true
  has_many :reports

  before_create :default_settings #, :generate_authentication_token
  after_create :install, :create_default_reminder

  # delegate :appointments, :classes: :products # sti

  def tz
    tz = ActiveSupport::TimeZone.new(timezone)
    if tz.nil?
      Rails.logger.warn "TimeZone for #{subdomain} not found: #{timezone}. Defaulting to UTC."
      tz = ActiveSupport::TimeZone.new('Etc/UTC')
    end
    tz
  end

  def tzinfo
    tz.tzinfo
  end

  def local_time
    tz.now
  end

  def settings=(options)
    unless options.nil?
      old = settings
      self.settings_yaml = OpenStruct.new(
        :wizard => options['wizard'] || 'inactive',
        :quantity_range => options['quantity_range'] || old.quantity_range,
        :message_booked_out => options['message_booked_out'] || old.message_booked_out,
        :message_blacked_out => options['message_blacked_out'] || old.message_blacked_out,
        :message_unscheduled => options['message_unscheduled'] || old.message_unscheduled,
        :message_unavailable => options['message_unavailable'] || old.message_unavailable,
        :message_closed => options['message_closed'] || old.message_closed,
        :df => options['df'] || old.df,
        :region => options['region'] || old.region,
        :theme => options['theme'] || old.theme
      ).to_yaml
    end
  end

  #when you want a shop to get a note about an action, like a successful job, pass in the_message you want them to see.
  # if it's something for a shop to do and is therefore actionable, pass true in is_actionable.
  def notifier(the_message = "",  info_hash = {})
    shopnotes_hash = {:message => the_message, :actionable => info_hash[:actionable], :shop_id => id, :noteable_id => info_hash[:noteable_id], :noteable_type => info_hash[:noteable_type] }
    ActiveSupport::Notifications.instrument("shopnotes.notifier", shopnotes_hash
                                            )
  end

  def settings
    if self.settings_yaml.blank?
      h = Hash.new
      h["wizard"] = "inactive"
      h["quantity_range"] = "no"
      h["message_booked_out"] = "Booked Out"
      h["message_blacked_out"] = "Blacked Out"
      h["message_unscheduled"] = "Unscheduled"
      h["message_unavailable"] = "Unavailable"
      h["message_closed"] = "Closed"
      h["df"] = "mm/dd/yy"
      h["region"] = ""
      h["theme"] = "smoothness"
      h
    else
      YAML::load(self.settings_yaml)
    end
  end

  def settings_json
    ActiveSupport::JSON.encode(settings.marshal_dump).html_safe
  end

  def template(name)
    template = templates.find_by_name(name.to_s.gsub(/[_-]/, ' ').capitalize)

    # if template doesn't exist create it
    unless template
      template = LiquidTemplate.new
      template.name = name.to_s.gsub(/[_-]/, ' ').split.map(&:capitalize).join(' ')
      template.body = File.read("#{Rails.root}/db/templates/#{name}.liquid")
      template.shop = self
      template.save
    end

    template
  end

  def install
    Delayed::Job.enqueue ShopInstallJob.new(id)
  end

  def create_default_reminder
    template = LiquidTemplate.create(
        shop: self,
        body: File.read("#{Rails.root}/db/templates/reminder.liquid"),
        name: 'Booking Reminder',
        category: TemplateCategory::REMINDER,
        channel: TemplateChannel::EMAIL,
        subject: 'Booking Reminder'
    )
    ReminderConfig.create(
        trigger_type: TriggerType::BEFORE_START,
        liquid_template_id: template.id,
        shop: self
    )
  end

  def resync_timezone
    external do
      store = ShopifyAPI::Shop.current
      self.timezone = store.timezone[12..store.timezone.length]
      self.save
    end
  end

  def resync_products
    products.each {|p| p.resync}
  end

  def resync_booking_date_ranges
    bookings.where('events.start > ?', DateTime.now).each do |b|
      minmax = b.booking_items.collect{|bi| [bi.start, bi.finish]}.flatten.minmax
      bookings.find(b.id).sync_booking_dates if minmax[0] != b.start || minmax[1] != b.finish
    end
  end

  def datetime_parser
    DateTimeParser.new(self)
  end

  def lookup_product_availability(start, finish, the_query)
    the_products = products.search_products(the_query)
    # cache key for a shop's products is the count (accounts for inserts/deletes) and updated_at (accounts for changes in capacity)
    product_ids = the_products.map(&:external_id)
    lookup_availability(start,finish, product_ids)
  end

  def lookup_availability(start, finish, product_ids)
    bta_product_ids = products
                      .where(:external_id => product_ids.flatten)
                      .pluck(:id)
    calc = AvailabilityCalculator2.new(self, start, finish, bta_product_ids)
    calc.calculate()

    # cache_key = availability_cache_key(product_ids, start, finish)
    #
    # Rails.cache.fetch(cache_key, :expires_in => Rails.env.production? ? 1.month : 1.minute) do
    #   # new availability calculator uses bta product ids
    #   bta_product_ids = products.where(:external_id => product_ids).pluck(:id)
    #   calc = AvailabilityCalculator2.new(self, start, finish, bta_product_ids)
    #   calc.calculate()
    # end
  end

  # these keys represent anything that can change that would change how availability is calculated - count (accounts for inserts/deletes) and max(updated_at) accounts for edit changes
  def availability_cache_key(product_ids, start, finish)
    products_cache_key = products.where(:external_id => product_ids).pluck_all("COUNT(*)", "MAX(updated_at)").flatten.first.values.map(&:to_i).join('-')
    events_cache_key = events.where(:external_product_id => product_ids + [nil]).pluck_all("COUNT(*)", "MAX(updated_at)").flatten.first.values.map(&:to_i).join('-')
    event_dates_cache_key = event_dates.where(:external_product_id => product_ids + [nil]).where('finish > ? and start < ?', start, finish).pluck_all("COUNT(*)", "MAX(updated_at)").flatten.first.values.map(&:to_i).join('-')
    constraints_cache_key = ResourceConstraint.joins(:resource).where(:resources => {:shop_id => id}).pluck_all("COUNT(*)", "MAX(resource_constraints.updated_at)").flatten.first.values.map(&:to_i).join('-')
    allocations_cache_key = ResourceAllocation.joins(:resource).where(:resources => {:shop_id => id}).pluck_all("COUNT(*)", "MAX(resource_allocations.updated_at)").flatten.first.values.map(&:to_i).join('-')
    cache_key = [self.updated_at, start, finish, product_ids, products_cache_key, events_cache_key, event_dates_cache_key, constraints_cache_key, allocations_cache_key]
  end

  #use this and fix something is mucked up with blank prod ids
  def empty_products_all_blackouts(start, finish)
    newstyle = blackouts.between(start,finish) #
    old = events.old_blackouts(start, finish)
    #does this send double nils? no because each one is different
    newstyle + old
  end

  def generate_shop_calendar_code
    hmac_sha1(subdomain, subdomain + id.to_s)
  end

  def compare_calendar_code(the_code)
    the_code == generate_shop_calendar_code
  end

  def hmac_sha1(data, secret)
    OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha1'), secret.encode("ASCII"), data.encode("ASCII"))
  end

  # product_ids is an array of BTA product ids
  def all_blackouts(start, finish, product_ids = [])
    # TODO: get rid of EventDate
    newstyle = blackouts.includes([:product, :variant]).where('event_dates.finish > ? and event_dates.start < ?', start, finish)
    newstyle = newstyle.where(:product_id => product_ids + [nil]) unless product_ids.empty?

    old = Event.where(:type => "OldBlackout").where(:shop_id => self.id).where('events.finish > ? and events.start < ?', start, finish)
    old = old.includes(:product).where(:product_id => product_ids + [nil]) unless product_ids.empty?

    newstyle.all + old.all
  end

  def has_class_profile_products?
    products.exists?(:profile => 'class')
  end

  def select_date_format
    df = settings.df || 'mm/dd/yy'
    df.sub('mm', '%m').sub('dd', '%d').sub('yy', '%Y')
  end

  def reset_variant_durations
    products.each do |p|
      p.reset_variant_durations
    end
  end

  def external(&block)
    ::NewRelic::Agent.add_custom_attributes(:account => subdomain)
    old_ar_site = ShopifyAPI::Base.site
    begin

app/views/reports/v2/_booking.html.erb
<% booking = item.booking %>
<tr>
  <td ><%= check_box_tag "booking_ids[]", booking.id, false, class: 'bookings_ids' %></td>
  <% @fields.each do |field|%>
    <td><%= field_render(field, item) %></td>
  <% end %>
</tr>

app/views/reports/v2/_enrollment.html.erb
<tr>
  <td>
    <span class="nowrap">
        <i class="no-print fa <%= "#{enrollment.payment_status == 2 ? 'fa-calendar' : 'fa-clock-o'}"%>" %></i>
      <%= link_to enrollment.booking_id, edit_booking_path(enrollment.booking_id), title: enrollment.payment_status == 2 ? 'Confirmed' : 'Reserved' %>
    </span>
  </td>
  <td>
    <div class="nowrap">
      <i class="no-print fa fa-envelope"></i>
      <%= mail_to enrollment.email, enrollment.name, :subject => enrollment.class_name %>
    </div>
  </td>
  <td>
    <% unless enrollment.phone.blank? %>
      <div class="nowrap">
        <i class="no-print fa fa-phone"></i>
        <a href="tel:<%= enrollment.phone %>"><%= enrollment.phone %></a>
      </div>
    <% end %>
  </td>
  <td>
    <%= check_box_tag 'attended', enrollment.booking_id , enrollment.attended?, :class => 'attendance-check' %>
  </td>
</tr>

app/views/reports/v2/_form.html.erb
<%= render 'common/v2/error_messages', :object => f.object %>
<div class="form-group">
  <label class="col-sm-2 control-label" for="products">Report Name</label>
  <div class="col-sm-10">
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-2 control-label" for="products">Select Fields</label>
  <div class="col-sm-10">
    <%= f.select :fields, options_for_select(fields_for_select), {}, { class: 'form-control chosen-select', multiple: true,  tabindex: "4"}  %>
  </div>
</div>

<div class="hr-line-dashed"></div>
<div class="form-group">
  <div class="col-sm-4 col-sm-offset-2">
    <%= link_to "Close", admin_reports_path, class: "btn btn-white" %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
</div>


<% content_for :javascript do %>

  <script>

    $( document ).ready(function() {
      $(".chosen-select").chosen({width: "550px"});
      $('.chosen-select').val(<%= raw @report.fields %>).trigger('chosen:updated');
      var validation = $("#edit_report").validate({
        rules: {
          'report[name]': {
            required: true
          }
        }
      });

      $( "#edit_report" ).submit(function( event ) {
        if(validation.errorList.length == 0)
          return;
        else event.preventDefault();
      });

    });

  </script>
<% end %>

app/views/reports/v2/_report.html.erb
<tr>
  <td><%= report.name %></td>
  <td><%= report.fields.map{ |field| Report::FIELDS[field][:text]}.join(', ') %></td>
  <td>
    <%= link_to content_tag(:i, '', :class => "fa fa-pencil"), edit_admin_report_path(report) %>
    <%= link_to content_tag(:i, '', :class => "fa fa-remove"), report, :data => {:confirm => 'Are you sure?'}, :class => 'ajax-delete' %>
  </td>
</tr>

app/views/reports/v2/edit.html.erb
<%= render partial: 'common/breadcrumbs',
           locals: {
               section: 'Reports',
               crumbs: [
                   {title: 'Configuration', path: ''},
                   {title: 'Runsheet reports'},
                   {title: 'Edit'}
               ]
           } %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-content">
          <%= form_for(@report, :url => admin_report_path(@report), :html => { class:"no-print form-horizontal" }) do |f|%>
            <%= render partial: 'reports/v2/form', :locals => {:f => f} %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/v2/enrollments.html.erb
<%= render partial: 'common/breadcrumbs',
           locals: {
               section: 'Bookings',
               crumbs: [
                   {title: 'Bookings', path: admin_events_path},
                   {title: 'Enrollments'}
               ]
           } %>


<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <%= render '/reports/v2/enrollments_filter' %>


      <div class="dataTables_wrapper">
        <% if @enrollments.empty? && @filter.present? %>
          <div class="alert alert-info">
            <span class="icon"></span>
            <p><strong>No bookings:</strong> There are no enrollments for this class.</p>
          </div>
        <% end %>

        <% unless @enrollments.empty? %>
          <table class="table table-striped">
            <thead>
            <tr>
              <th>Booking</th>
              <th>Customer</th>
              <th>Phone</th>
              <th>Attended?</th>
            </tr>
            </thead>
            <tbody>
            <% @enrollments.each do |enrollment| %>
              <%= render partial: 'reports/v2/enrollment', locals: { enrollment: enrollment } %>
            <% end %>
            </tbody>
          </table>
          <div class="no-print">
            <%= paginate @enrollments, theme: 'v2'%>
          </div>

          <div class="tab-footer clear no-print">
            <div class="fl">
              <a href="#" onClick="window.print(); return false;" class="btn btn-default submit">Print Page</a>
              <%= link_to "PDF", enrollments_path(request.parameters.symbolize_keys.merge({:format => :pdf})), :class => 'btn btn-default submit' %>
              <%= link_to "Excel", enrollments_path(request.parameters.symbolize_keys.merge({:format => :xls})), :class => 'btn btn-default submit' %>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>


<script id="schedule-template" type="text/html">
  <tr>
    <td><input type="radio" value="" name="event" data-start='${ moment(start).format("YYYY-MM-DDTHH:mm") }'  data-finish='${ moment(end).format("YYYY-MM-DDTHH:mm") }'></td>
    <td>${ moment(start).format('YYYY-MM-DD HH:mm') }</td>
    <td>${ bookingCount }</td>
    <td>${ capacity }</td>
  </tr>
</script>

<% content_for :javascript do -%>
<%= javascript_include_tag 'reports-helper.js' %>

<script>
    $('.attendance-check').bind('change', function () {
        $.ajax({
            url: '/bookings/' + this.value + '/attendance',
            type: 'POST',
            data: {"attended": this.checked}
        });
    });

    function selectDates() {
      var start = $('#start'),
          selected = $('input[type="radio"][name="event"]:checked');

      if (selected.length > 0) {
        start.val(selected.attr('data-start'));
      }
    }

    function getParameterByName(name) {
        var match = RegExp('[?&]' + name + '=([^&]*)').exec(window.location.search);
        return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
    }

    function loadSchedule() {
        var external_product_id = $('#products option:selected').attr('data-external-id'),
            external_variant_id = $('#variants option:selected').attr('data-external-id');

        if (external_product_id) {
            $('#event-instructions').hide();

            $.getJSON("/availability/schedule.json?callback=?", {
                products: external_product_id || '',
                variants: external_variant_id || '',
                start: moment(new Date()).format('YYYY-MM-DD'),
                finish: moment(new Date()).add(6, 'months').format('YYYY-MM-DD')
            }, function (data) {
                var table = $('#upcoming-classes').find('tbody'),
                    events = $.map(data.schedule, function(event) {
                        event.start = new Date(event.start[0], event.start[1] - 1, event.start[2], event.start[3], event.start[4], event.start[5]);
                        event.end = new Date(event.end[0], event.end[1] - 1, event.end[2], event.end[3], event.end[4], event.end[5]);
                        return event;
                    });

                table.empty();

                for (var i = 0; i < events.length && i <= 30; i++) { // display up to the next 30 events
                    $('#schedule-template').tmpl(events[i]).appendTo(table);
                }

                var startParam = getParameterByName('start');
                if (startParam) {
                    $('input[type="radio"][name="event"][data-start="' + unescape(startParam) + '"]').prop('checked', 'true');
                } else {
                    $('input[type="radio"][name="event"]:first').prop('checked', 'true');
                }

                selectDates();

                if (events.length == 0) {
                    $('#no-events').show();
                    $('#upcoming-classes').hide();
                } else {
                    $('#no-events').hide();
                    $('#upcoming-classes').show();
                }
            });
        } else {
            $('#event-instructions').show();
            $('#upcoming-classes').hide();
            $('#no-events').hide();
            $('.dataTables_wrapper').hide(); // hide results from previous search
        }
    }

    $('#products, #variants').bind('change', function() {
        loadSchedule();
    });

    loadSchedule();

    $('#upcoming-classes').on('change', 'input[type="radio"][name="event"]', function() {
        selectDates();
    });

    <% if @filter.present? %>
    $('#start').datepicker('setDate', new Date('<%= @filter.start %>'));
    <% end %>
</script>
<% end %>

app/views/reports/v2/index.html.erb
<%= render partial: 'common/breadcrumbs',
           locals: {
               section: 'Reports',
               crumbs: [
                   {title: 'Configuration', path: ''},
                   {title: 'Reports'}
               ]
           } %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">

    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-content">
          <%= link_to 'Add Report', new_admin_report_path, class: "btn btn-primary"  %>
          <table class="table table-striped table-bordered table-hover " id="editable">
            <thead>
            <tr>
              <th>Name</th>
              <th>Fields</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <%= render partial: 'reports/v2/report', collection: @reports %>
            <% if @reports.empty? %>
              <tr>
                <td colspan="4">No reports</td>
              </tr>
            <% end %>
            </tbody>
            <tfoot>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>