config/routes.rb
class Subdomain
  def self.matches?(request)
    request.subdomain.present? && request.subdomain != 'www'
  end
end

Bookthatapp::Application.routes.draw do
  root :to => 'home#index'

  mount StripeEvent::Engine => '/stripe' # gem 'stripe-event'

  devise_for :users, controllers: {
        sessions: 'users/sessions', registrations: "users/registrations"
      }
  resources :users

  get "locations/index"

  get 'status' => "home#status"
  get 'change_ui' => 'home#change_ui'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  scope '/hooks' do
    post 'shop/update'         => 'hooks#shop_update'
    post 'app/uninstalled'     => 'hooks#uninstall'
    post 'orders/create'       => 'hooks#order'
    post 'orders/paid'         => 'hooks#paid'
    post 'orders/cancelled'    => 'hooks#cancelled'
    post 'orders/update'       => 'hooks#orders_update'
    post 'products/update'     => 'hooks#update'
    post 'products/delete'     => 'hooks#delete'
    post 'mail'                => 'hooks#mail'
  end

  scope '/apps' do
    get 'bookthatapp(/:action(/:id))', :controller => 'proxy'
  end

  resources :calendar, only: [:index]
  get '/navigate(/:action(/:id))', :controller => 'navigate'

  constraints(Subdomain) do
    resources :events, only: [:index]

    resources :bookings do
      member do
        put 'reminder'
        put 'sms'
      end
      collection do
        post 'send_reminders', as: :send_reminders
      end
    end

    resources :resource_groups, :users, :product_imports, :blackouts, :locations, :accounts

    resources :shops do
      member do
        get 'locations'
      end
    end

    resources :resources do
      resources :schedules
    end


    resources :bookings do
      member do
        get 'ticket'
        get 'email_activity'
        post 'attendance', :constraints => {:format => /(json)/}
      end
    end

    resources :products do
      resources :reservations
      resources :waitlists
      resources :variants do
        post 'reset', :on => :collection
      end

      collection do
        get 'autocomplete'
      end
      resources :terms, except: [:index]
    end

    resource :availabilities, only: [:index], defaults: { format: 'json' } do
      collection do
        get 'capacity'
        get 'preview'
        get 'schedule'
      end
    end

    resources :templates do
      collection do
        get 'new_reminder'
      end
      member do
        get 'site'
        get 'email'
      end
    end

    resource :feedback, only: [:new, :create]
    resource :embed, only: [:new, :create]

    resources :charges do
      collection do
        patch 'approve_install'
        get 'confirm'
        get 'install'
        patch 'subscribe'
        patch 'cancel'
        get 'installation'
      end
    end

    post 'charges/cancelled(/:id)' => 'charges#cancelled', :as => :cancel_installation
    post 'charges/cancel_pending(/:id)' => 'charges#cancel_pending', :as => :cancel_pending_charge

    get '/shop/install' => 'shops#install'

    scope :reports do
      get 'runsheet' => 'reports#runsheet', :as => :runsheet
      get 'enrollments' => 'reports#enrollments', :as => :enrollments
      get 'gantt' => 'reports#gantt'
    end


    resource :javascripts, only: [:index] do
      member do
        get 'bta'
        get 'wizard'
      end
    end

    get 'settings' => 'settings#index'
    resource :settings, only: [:index] do
      member do
        get 'hours'
        post 'update'
        post 'update_hours'
      end
      # resource :hours
    end

    scope :doco do
      get 'install' => 'doco#install'
      get 'product' => 'doco#product'
      get 'cart' => 'doco#cart'
      get 'email' => 'doco#email'
      get 'compatibility' => 'doco#compatibility'
      get 'css' => 'doco#css'
      get 'themes' => 'doco#themes'
    end

    get '/tests/:action', :controller => 'tests'
    resources :reports

    scope '/admin', :as => :admin do
      get 'dashboard', to: 'events#index'
      get 'charges'              => 'charges#index'
      get 'charges/confirm'      => 'charges#confirm'
      get 'charges/install'      => 'charges#install'
      get 'charges/installation' => 'charges#installation'
      post 'charges/cancelled(/:id)'      => 'charges#cancelled', :as => :cancel_installation
      post 'charges/cancel_pending(/:id)' => 'charges#cancel_pending', :as => :cancel_pending_charge

      get 'events/resources' => 'events#resources'

      resources 'events', 'blackouts', 'locations'
      get 'reports/runsheet'      => 'reports#runsheet', :as => :runsheet
      get 'reports/enrollments'   => 'reports#enrollments', :as => :enrollments

      resources :reports

      resources :products do
        resources :reservations
        resources :waitlists
        resources :variants do
          post 'reset', :on => :collection
        end

        collection do
          get 'autocomplete'
        end
        resources :terms, except: [:index]
      end


      resources :product_imports
      resources :resources do
        resources :schedules
      end

      resources :templates do
        get 'new_reminder', :on => :collection
      end

      resources 'doco', only: [:index] do
        collection do
          get 'install'
          get 'cart'
          get 'picker'
          get 'product'
          get 'availability'
          get 'css'
          get 'widgets'
          get 'themes'
          post 'snippet'
          get 'email'
          get 'compatibility'
        end
      end

      resources :settings, only: [:index, :update] do
        post 'update_settings'
        collection do
          post 'update_hours'
          get 'hooks'
          get 'scripts'
          get 'hours'
        end
      end

      resources :bookings do
        member do
          put 'reminder'
          put 'sms'
        end
        collection do
          post 'send_reminders', as: :admin_send_reminders
        end
      end

    end


    match '/:controller(/:action(/:id))', via: [:get, :post, :patch]
  end

  namespace :api do
    namespace :v1 do
      get 'availability' => 'availability#index'
      resources :bookings, only: [:index, :show]
    end
  end

  get 'status' => 'home#status'
  get '/404' => 'errors#error_404'
  get '/422' => 'errors#error_422'
  get '/429' => 'errors#error_429'
  get '/500' => 'errors#error_500'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  get '/:controller(/:action(/:id))'

  # otherwise show not found
  get ':url' => 'application#not_found', :constraints => { :url => /.*/ }
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  force_ssl if Rails.env.production?
  include SpecificRendering

  def index
    @charges = []
    @delete_products_count = @account.products.count - Bookthatapp::Application.config.limited_plan_max_products

    @account.external do
      begin
        charges = ShopifyAPI::RecurringApplicationCharge.all || []
        @charges = charges
      rescue ActiveResource::Redirection
        @msg = "There is a problem with your Shopify plan so we are unable to show the charge history at this time. Please login to your Shopify Account for further instructions."
      end
    end
  end

  def installation
    if current_account.stripe_customer_id.nil?
      @stripe_charges = []
    else
      @customer_card = Stripe::Customer.retrieve(current_account.stripe_customer_id)
      @stripe_charges = Stripe::Charge.all(customer: @customer_card.id)
    end

    @account.external do
      @charges = ShopifyAPI::ApplicationCharge.all || []
    end

  end

  def confirm
    @account.external do
      charge = ShopifyAPI::RecurringApplicationCharge.find(params[:charge_id])
      if charge
        if charge.status == 'accepted'
          charge.activate
          @account.update_attribute :charge_id,  params[:charge_id].to_i
          redirect_to events_path(:subdomain => @account.subdomain)
        else
          flash[:notice] = 'Declined'
          redirect_to :action => 'index'
        end
      else
        flash[:notice] = 'Invalid subscription request'
        redirect_to :action => 'index'
      end
    end
  end

  def cancel
    @account.external do
      charge = ShopifyAPI::RecurringApplicationCharge.current
      if charge
        flash[:notice] = 'Your subscription has been cancelled.'
        @account.update_attribute :charge_id, -1
        charge.cancel
      else
        flash[:notice] = 'Subscription not found.'
      end
    end

    redirect_to :action => 'index'
  end

  def approve_install
    @account.external do
      charge = ShopifyAPI::ApplicationCharge.create(
          :name => 'BookThatApp Installation',
          :return_url => install_charges_url(:subdomain => current_subdomain),
          :price => Bookthatapp::Application.config.install_price,
          :test => Rails.env.development? || @account.subdomain == "legros-parker-and-harris6290")

      return redirect_to charge.confirmation_url
    end
  end

  def install # called after approve_install
    @account.external do
      charge = ShopifyAPI::ApplicationCharge.find(params[:charge_id])
      if charge.status == "accepted"
        charge.activate
        Notifier.install_email(@account).deliver_now
        flash[:notice] = "Your payment has been processed. Please check your email for a confirmation message and next steps."
      else
        flash[:notice] = "Payment request declined."
      end
      redirect_to :action => 'installation'
    end
  end

  def cancel_pending
    @account.external do
      charge = ShopifyAPI::RecurringApplicationCharge.find(params[:id])
      if charge
        charge.cancel
        flash[:notice] = 'Pending charge cancelled.'
      end
    end
    redirect_to :action => 'index'
  end

  def subscribe
    @account.external do
      charge = ShopifyAPI::RecurringApplicationCharge.create(
          :name => 'BookThatApp Subscription',
          :return_url => confirm_charges_url(:subdomain => current_subdomain),
          :price => Bookthatapp::Application.config.price,
          # :trial_days => Bookthatapp::Application.config.trial_period,
          :test => Rails.env.development? || @account.subdomain == "legros-parker-and-harris6290")

      return redirect_to charge.confirmation_url
    end
  end

  def stripe_install
    token = params[:stripeToken] # Get the credit card details submitted by the form
    redirect_to :action => :installation if token.nil?

    begin
      customer_id = current_account.stripe_customer_id
      if customer_id.nil?
        # Create a Customer
        customer = Stripe::Customer.create(
          :card => token,
          :description => "#{current_account.subdomain}",
          :email => params[:email]
        )
        customer_id = customer.id

        # Save the customer ID
        current_account.stripe_customer_id = customer_id
        current_account.save
      end

      # Charge the Customer
      stripe_install_charge(customer_id)

      flash[:notice] = "Payment success"
      redirect_to :action => :install_survey

    rescue  Stripe::InvalidRequestError => ire
      flash[:notice] = "#{ire.message}"
      redirect_to :action => :installation
    rescue Stripe::CardError => ce
      flash[:notice] = "#{ce.message}"
      redirect_to :action => :installation
    end
  end

  def stripe_install_charge(customer_id)
    charge = Stripe::Charge.create(
        :amount => (Bookthatapp::Application.config.install_price * 100).to_i, # amount in cents
        :currency => "usd",
        :customer => customer_id,
        :description => "BookThatApp Installation: #{current_account.subdomain}",
        :metadata => {:account => current_account.subdomain}
    )

    $gabba.transaction(charge.id, Bookthatapp::Application.config.install_price) if Rails.env.production?
  end

  def stripe_repeat_install
    stripe_install_charge(current_account.stripe_customer_id)
  end

  def stripe_delete_customer
    cu = Stripe::Customer.retrieve(current_account.stripe_customer_id)
    cu.delete

    current_account.stripe_customer_id = nil
    current_account.save

    redirect_to :action => :installation
  end

  # stripe webhook
  def cancelled

  end

  def install_survey

  end
end

app/views/charges/index.html.erb
<h1>Billing</h1>

<div class="content-box">
  <div class="box-header clear">
    <h2>Your subscription</h2>
  </div>
  <div class="box-body clear">
    <div>
      <p>You are currently on the <strong><%= current_account.charge_id == -1 ? 'trial' : current_account.charge_id == 0 ? 'free' : 'paid' %></strong> plan.</p>

      <% if @plan_exceeded %>
          <div class="notification note-info"><span class="icon"></span>
            <p><strong>Trial Plan Limit Exceeded</strong>: You now have <%= @bookings_count %> bookings which exceeds the maximum number of
              products (<%= Bookthatapp::Application.config.limited_plan_max_products %>) or bookings (<%= Bookthatapp::Application.config.limited_plan_max_bookings %>)
              available under the trial plan. To continue using BookThatApp please upgrade to the paid plan.</p>
          </div>
          <%= form_for current_account, :url => {:action => "subscribe"}, :class => "fr" do |form| %>
              <%= hidden_field_tag 'ga_client_id', '', :class => 'ga-client-id' %>
              <p><%= form.submit 'Upgrade to a paid BookThatApp subscription', :class => "submit" %></p>
          <% end %>
      <% else %>
          <% if @msg %>
              <div class="notification note-error"><span class="icon"></span>
                <p><strong>Please note</strong>: <%= h @msg %></p>
              </div>
          <% end %>

          <% unless @charges.size == 0 %>
              <table class="styled">
                <caption>Charge History</caption>
                <thead>
                <tr>
                  <th>Date</th>
                  <th>Price</th>
                  <th>Status</th>
                  <!-- <th></th> -->
                </tr>
                </thead>
                <tbody>
                <% @charges.each do |charge| %>
                    <% unless charge.status == 'pending' %>
                        <tr>
                          <% time = to_time(charge.created_at) %>
                          <td><%= l time, :format => :short %> (<%= time_ago_in_words(time) %>  ago)</td>
                          <td>$<%= charge.price %></td>
                          <td><%= charge.status.capitalize %></td>
                          <!--
                  <td>
                    <% if charge.status == 'pending' %>
                        <%= button_to "Cancel", cancel_pending_charge_path(charge), :class => 'submit' %>
                    <% end %>
                  </td>
                  -->
                        </tr>
                    <% end %>
                <% end %>
                </tbody>
              </table>
          <% end %>

          <% if current_account.charge_id < 1 %>
              <%= form_for current_account, url: subscribe_charges_path, class: 'fr' do |form| %>
                  <%= hidden_field_tag 'ga_client_id', '', :class => 'ga-client-id' %>
                  <p><%= form.submit 'Upgrade to a paid BookThatApp subscription', :class => 'submit' %></p>
              <% end %>
          <% end %>
          <% if current_account.charge_id > 0 %>
              <%
                msg = "The free trial plan is limited to #{Bookthatapp::Application.config.limited_plan_max_products} products and #{Bookthatapp::Application.config.limited_plan_max_bookings} bookings."

                if @delete_products_count > 0
                  msg += " Cancelling your subscription will result in the deletion of #{@delete_products_count} products and their associated bookings."
                end
              %>

              <%= form_for current_account, :url => {:action => 'cancel'}, :class => 'fr' do |form| %>
                  <%= hidden_field_tag 'ga_client_id', '', :class => 'ga-client-id' %>
                  <p><%= form.submit 'Cancel Subscription', :class => 'submit', :title => msg %>
                  </p>
              <% end %>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/charges/install_survey.html.erb
<iframe src="https://docs.google.com/forms/d/1LTnaDssl6fjlKz75h_BNBXHRnLfwVab95lxcwi8mBwc/viewform?entry.939755775=<%= current_account.subdomain %>&embedded=true" width="100%" height="700" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
<%= link_to 'Back', install_path, class: 'submit' %>

app/views/charges/installation.html.erb
<h1>Billing</h1>

<div class="content-box">
  <div class="box-header clear">
    <h2>Purchase Installation</h2>
  </div>
  <div class="box-body clear">
    <div class="half fl">
      <p>For a one time installation fee of <strong>$US <%= sprintf('%.2f', Bookthatapp::Application.config.install_price) %></strong> we
        can install BookThatApp into your current theme for you. Installation includes:</p>
      <ul>
        <li>adding one of the supported date and/or time picker widgets to your product page</li>
        <li>updating the cart page to show selected dates</li>
        <li>modifying the customer notification email template</li>
      </ul>
      <br/>
      <div class="notification note-attention"><span class="icon"></span>
        <p>Please note the following conditions:</p>
        <ul style="margin-left: 10px;">
          <li>Installation purchase is for <strong>1 theme only</strong>. If you change your theme you will need to reinstall the App.</li>
          <li>A maximum of <strong>2 revisions</strong> is permitted. Please ensure all requirements are specified before we begin the install.</li>
        </ul>
      </div>

      <% if only_admin %>
          <% if current_account.stripe_customer_id.nil?  %>
          <p>
            <%= form_for current_account, :url => {:action => "stripe_install"} do |form| %>
                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="<%= Bookthatapp::Application.config.stripe_publish_key %>"
                        data-amount="<%= (Bookthatapp::Application.config.install_price * 100).to_i %>"
                        data-name="BookThatApp"
                        data-description="BookThatApp Installation ($<%= sprintf('%.2f', Bookthatapp::Application.config.install_price) %>)"
                        data-image="/128x128.png">
                </script>
            <% end %>
          </p>
          <% else %>
          <p>
            <%= form_for current_account, :url => {:action => "stripe_delete_customer"} do |form| %>
                <%= form.submit "Remove Card (ending in #{@customer_card.cards.first.values[2] })", :class => "submit fr" %>
            <% end %>

            <%= form_for current_account, :url => {:action => "stripe_repeat_install"} do |form| %>
                <%= form.submit 'Purchase Another Installation', :class => "submit" %>
            <% end %>
          </p>
          <% end %>
      <% end %>

      <p>
      <%= form_for current_account, url: approve_install_charges_path, :class => "fr" do |form| %>
          <%= form.submit 'Purchase BookThatApp Installation', :class => "submit" %>
      <% end %>
      </p>
      <p>
        The purchase charge will be automatically appear in your next Shopify invoice.
      </p>

      <% unless only_admin %>
      <p>We will contact you after your installation request and confirm how BookThatApp will work with your products.</p>
      <div class="notification note-info"><span class="icon"></span>
        <p>Please invite <strong>support@shopifyconcierge.com</strong> to your store after you have completed purchase.</p>
      </div>
      <% end %>
    </div>

    <div class="half fr">
      <% if only_admin %>
          <% if @stripe_charges.count == 0 %>
              <div class="notification note-info"><span class="icon"></span>
                <p>Your purchase history will appear here after you have made a payment.</p>
              </div>
          <% else %>
              <table class="styled">
                <caption>Charge History</caption>
                <thead>
                <tr>
                  <th>Date</th>
                  <th>Card</th>
                  <th>Price</th>
                  <th>Status</th>
                </tr>
                </thead>
                <tbody>
                <% @stripe_charges.each do |charge| %>
                    <tr>
                      <% time = DateTime.strptime(charge.created.to_s, '%s') %>
                      <td><%= l time, :format => :short %><br>(<%= time_ago_in_words(time) %>  ago)</td>
                      <td><%= charge.card.brand %> **** **** **** <%= charge.card.last4 %> <%= charge.card.exp_month %>/<%= charge.card.exp_year %></td>
                      <td>
                        <% if charge.refunded %><strike><% end %>$<%= sprintf('%.2f', (charge.amount / 100).round(2)) %><% if charge.refunded %></strike><% end %>
                      </td>
                      <td><%= charge.description %></td>
                    </tr>
                <% end %>
                </tbody>
              </table>
          <% end %>
      <% end %>

      <% unless @charges.blank? %>
      <table class="styled">
        <caption>Charge History</caption>
        <thead>
        <tr>
          <th>Date</th>
          <th>Price</th>
          <th>Status</th>
        </tr>
        </thead>
        <tbody>
        <% @charges.each do |charge| %>
            <% unless charge.status == 'pending' %>
            <tr>
                  <% time = to_time(charge.created_at) %>
              <td><%= l time, :format => :short %> (<%= time_ago_in_words(time) %>  ago)</td>
              <td>$<%= charge.price %></td>
              <td><%= charge.status.capitalize %></td>
            </tr>
            <% end %>
        <% end %>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>